# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Real General Practice
email: info@code4health.org
description: > # this means to ignore newlines until "baseurl:"
  This site is under construction
baseurl: "https://fishy1976.github.io/Fishy1976.RGP.github.io/" # the subpath of your site, e.g. /blog
url: "https://Fishy1976.github.io/Fishy1976.RGP.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  Fishy1976

collections:
 - teams
 - registrations

gems:
  - jekyll-archives

# Build settings
markdown: kramdown
exclude: ["README.md"]
include: ['_pages']

jekyll-archives:
  enabled: all
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
